### ISSUE TITLE
Compilation issues when component importing third-party components or services

### ISSUE THREAD

**Issue by rainerhahnekamp** [testronaut/testronaut#73]
@yjaaidi: I created a simple component, which injects `PLATFORM_ID` and the `MatButton` directive. 

You can find the PR including the test along failed GitHub actions in #72 

You are much (much) more familiar with that, so I will assign it to you. Hope that's fine.

The compilation fails with the following message:

```bash
> playwright test
  
  JIT compilation failed for injectable [class PlatformLocation]
  
  Error: The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
  
  The injectable is part of a library that has been partially compiled.
  However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
  
  Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
  Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
  or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
      at getCompilerFacade (/home/runner/work/testronaut/testronaut/node_modules/.pnpm/darwin_arm64-fastbuild-ST-199a4f3c4e20/bin/packages/core/src/compiler/compiler_facade.ts:45:11)
      at Module.ɵɵngDeclareFactory (/home/runner/work/testronaut/testronaut/node_modules/.pnpm/darwin_arm64-fastbuild-ST-199a4f3c4e20/bin/packages/core/src/render3/jit/partial.ts:107:20)
      at Function.<static_initializer> (/home/runner/work/testronaut/testronaut/node_modules/.pnpm/@angular+common@20.2.4_@angular+core@20.2.4_@angular+compiler@20.2.4_rxjs@7.8.2_zone.js@0.15.1__rxjs@7.8.2/node_modules/@angular/common/fesm2022/location.mjs:53:22)
      at /home/runner/work/testronaut/testronaut/node_modules/.pnpm/@angular+common@20.2.4_@angular+core@20.2.4_@angular+compiler@20.2.4_rxjs@7.8.2_zone.js@0.15.1__rxjs@7.8.2/node_modules/@angular/common/fesm2022/location.mjs:24:1
  
  Error: The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
  
  The injectable is part of a library that has been partially compiled.
  However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
  
  Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
  Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
  or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
      at getCompilerFacade (/home/runner/work/testronaut/testronaut/node_modules/.pnpm/darwin_arm64-fastbuild-ST-199a4f3c4e20/bin/packages/core/src/compiler/compiler_facade.ts:45:11)
      at Module.ɵɵngDeclareFactory (/home/runner/work/testronaut/testronaut/node_modules/.pnpm/darwin_arm64-fastbuild-ST-199a4f3c4e20/bin/packages/core/src/render3/jit/partial.ts:107:20)
      at Function.<static_initializer> (/home/runner/work/testronaut/testronaut/node_modules/.pnpm/@angular+common@20.2.4_@angular+core@20.2.4_@angular+compiler@20.2.4_rxjs@7.8.2_zone.js@0.15.1__rxjs@7.8.2/node_modules/@angular/common/fesm2022/location.mjs:53:22)
      at /home/runner/work/testronaut/testronaut/node_modules/.pnpm/@angular+common@20.2.4_@angular+core@20.2.4_@angular+compiler@20.2.4_rxjs@7.8.2_zone.js@0.15.1__rxjs@7.8.2/node_modules/@angular/common/fesm2022/location.mjs:24:1
```
